//go:build !ignore_autogenerated

/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package resource

import (
	"k8s.io/api/resource/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesGroup) DeepCopyInto(out *NamedResourcesGroup) {
	*out = *in
	if in.Quantities != nil {
		in, out := &in.Quantities, &out.Quantities
		*out = make([]NamedResourcesQuantity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StringSets != nil {
		in, out := &in.StringSets, &out.StringSets
		*out = make([]NamedResourcesStringSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IntSets != nil {
		in, out := &in.IntSets, &out.IntSets
		*out = make([]NamedResourcesIntSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesGroup.
func (in *NamedResourcesGroup) DeepCopy() *NamedResourcesGroup {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesInstance) DeepCopyInto(out *NamedResourcesInstance) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]v1alpha2.NamedResourcesAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]NamedResourcesGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesInstance.
func (in *NamedResourcesInstance) DeepCopy() *NamedResourcesInstance {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesIntSet) DeepCopyInto(out *NamedResourcesIntSet) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesIntSet.
func (in *NamedResourcesIntSet) DeepCopy() *NamedResourcesIntSet {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesIntSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesQuantity) DeepCopyInto(out *NamedResourcesQuantity) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesQuantity.
func (in *NamedResourcesQuantity) DeepCopy() *NamedResourcesQuantity {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesQuantity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesResources) DeepCopyInto(out *NamedResourcesResources) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]NamedResourcesInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedLimits != nil {
		in, out := &in.SharedLimits, &out.SharedLimits
		*out = make([]NamedResourcesGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesResources.
func (in *NamedResourcesResources) DeepCopy() *NamedResourcesResources {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedResourcesStringSet) DeepCopyInto(out *NamedResourcesStringSet) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedResourcesStringSet.
func (in *NamedResourcesStringSet) DeepCopy() *NamedResourcesStringSet {
	if in == nil {
		return nil
	}
	out := new(NamedResourcesStringSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceModel) DeepCopyInto(out *ResourceModel) {
	*out = *in
	if in.NamedResources != nil {
		in, out := &in.NamedResources, &out.NamedResources
		*out = new(NamedResourcesResources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceModel.
func (in *ResourceModel) DeepCopy() *ResourceModel {
	if in == nil {
		return nil
	}
	out := new(ResourceModel)
	in.DeepCopyInto(out)
	return out
}
